# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160411_0324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hoice',
            new_name='Choice',
        ),
    ]
