# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_test1_testlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestLink',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Test1',
            new_name='Test',
        ),
    ]
