# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160411_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='test1',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
